E_voting_system/E_voting_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from E_voting_system_app import views, AdminViews, CommitteeViews, VoterViews

from E_voting_system import settings

urlpatterns = [
    # HOD url path
    path('demo', views.showDemoPage),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.ShowLoginPage, name="show_login"),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user, name="logout"),
    path('doLogin', views.doLogin, name="do_login"),
    path('admin_home', AdminViews.admin_home, name="admin_home"),
    path('add_committee', AdminViews.add_committee, name="add_committee"),
    path('add_committee_save', AdminViews.add_committee_save, name="add_committee_save"),
    path('add_candidate', AdminViews.add_candidate, name="add_candidate"),
    path('add_candidate_save', AdminViews.add_candidate_save, name="add_candidate_save"),
    path('add_voter', AdminViews.add_voter, name="add_voter"),
    path('add_voter_save', AdminViews.add_voter_save, name="add_voter_save"),
    path('manage_committee', AdminViews.manage_committee, name="manage_committee"),
    path('manage_voter', AdminViews.manage_voter, name="manage_voter"),
    path('delete_voter/<str:voter_id>', AdminViews.delete_voter, name="delete_voter"),
    path('delete_committee/<str:committee_id>', AdminViews.delete_committee, name="delete_committee"),
    path('delete_candidate/<str:candidate_id>', AdminViews.delete_candidate, name="delete_candidate"),
    path('manage_candidate', AdminViews.manage_candidate, name="manage_candidate"),
    path('committee_home', CommitteeViews.committee_home, name="committee_home"),
    path('committee_profile', CommitteeViews.committee_profile, name="committee_profile"),
    path('committee_profile_save', CommitteeViews.committee_profile_save, name="committee_profile_save"),
    path('results', CommitteeViews.results, name="results"),
    path('candidate_result/<str:candidate_id>', CommitteeViews.candidate_result, name="candidate_result"),
    path('candidate_result_save', CommitteeViews.candidate_result_save, name="candidate_result_save"),
    path('voter_home', VoterViews.voter_home, name="voter_home"),
    path('voting_panel', VoterViews.voting_panel, name="voting_panel"),
    path('voter_profile', VoterViews.voter_profile, name="voter_profile"),
    path('voter_profile_save', VoterViews.voter_profile_save, name="voter_profile_save"),
    path('admin_profile', AdminViews.admin_profile, name="admin_profile"),
    path('admin_profile_save', AdminViews.admin_profile_save, name="admin_profile_save"),
    path('view_candidate/<str:candidate_id>', VoterViews.view_candidate, name="view_candidate"),
    path('view_candidate_save', VoterViews.view_candidate_save, name="view_candidate_save"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

E_voting_system/E_voting_system_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
'''class SessionYearModel(models.Model):
    id = models.AutoField(primary_key=True)
    session_start_year = models.DateField()
    session_end_year = models.DateField()
    object = models.Manager()'''


class CustomUser(AbstractUser):
    user_type_data = ((1, "Admin"), (2, "Committee"), (3, "Voter"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)


class Admin(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


'''
class Parents(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    father_occupation = models.CharField(max_length=255)
    # parent_roll_number = models.CharField(max_length=50)
    mother_occupation = models.CharField(max_length=255)
    parent_ph_no = models.CharField(max_length=10)
    fcm_token = models.TextField(default="")
    parent_address = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()
'''


class Committees(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    committee_number = models.CharField(max_length=50)
    dob = models.DateField()
    blood_group = models.CharField(max_length=10)
    qualification = models.CharField(max_length=50)
    gender = models.CharField(max_length=255)
    profile_pic = models.FileField()
    ph_no = models.CharField(max_length=10)
    address = models.TextField()
    fcm_token = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


'''
class Subjects(models.Model):
    id = models.AutoField(primary_key=True)
    subject_name = models.CharField(max_length=255)
    course_id = models.ForeignKey(Courses, on_delete=models.CASCADE, default=1)
    staff_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()
'''


class Voters(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    gender = models.CharField(max_length=255)
    voter_number = models.CharField(max_length=50)
    blood_group = models.CharField(max_length=10)
    profile_pic = models.FileField()
    ph_no = models.CharField(max_length=10)
    dob = models.DateField()
    fcm_token = models.TextField(default="")
    address = models.TextField()
    voter_status = models.TextField(default="No")
    cipher_text = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class Candidates(models.Model):
    id = models.AutoField(primary_key=True)
    gender = models.CharField(max_length=255)
    candidate_number = models.CharField(max_length=50)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    blood_group = models.CharField(max_length=10)
    profile_pic = models.FileField()
    ph_no = models.CharField(max_length=10)
    dob = models.DateField()
    fcm_token = models.TextField(default="")
    address = models.TextField()
    email = models.CharField(max_length=255)
    vote = models.CharField(max_length=255)
    message = models.CharField(max_length=255)
    ciphertext_candidates = models.TextField(default="1")
    vote_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(admin=instance)
        if instance.user_type == 2:
            Committees.objects.create(admin=instance, address="", profile_pic="", gender="", ph_no="",
                                      dob="2000-01-01", qualification="", blood_group="", committee_number="")

        if instance.user_type == 3:
            Voters.objects.create(admin=instance,
                                  address="", profile_pic="",
                                  gender="", ph_no="", dob="2000-01-01", blood_group="", voter_number="",
                                  voter_status="No", cipher_text="")


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    if instance.user_type == 2:
        instance.committees.save()
    if instance.user_type == 3:
        instance.voters.save()

E_voting_system/E_voting_system_app/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from E_voting_system_app.EmailBackEnd import EmailBackEnd


def showDemoPage(request):
    return render(request, "demo.html")


def ShowLoginPage(request):
    return render(request, "login_page.html")


def doLogin(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = EmailBackEnd.authenticate(request, username=request.POST.get("email"),
                                         password=request.POST.get("password"))
        if user != None:
            login(request, user)
            if user.user_type == "1":
                return HttpResponseRedirect('/admin_home')
            elif user.user_type == "2":
                return HttpResponseRedirect(reverse("committee_home"))
            elif user.user_type == "3":
                return HttpResponseRedirect(reverse("voter_home"))

        else:
            messages.error(request, "Invalid Login Details")
            return HttpResponseRedirect("/")


def GetUserDetails(request):
    if request.user != None:
        return HttpResponse("User : " + request.user.email + " usertype : " + str(request.user.user_type))
    else:
        return HttpResponse("Please Login First")


def logout_user(request):
    logout(request)
    return HttpResponseRedirect("/")

E_voting_system/E_voting_system_app/templates/admin_template/add_candidate_template.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Add Candidate
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Candidate</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_candidate_save" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-body">
                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>
                  <div class="form-group">
                    <label>Email address</label>
                    <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email" autocomplete="off">
                  </div>

                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="first_name" autocomplete="off">
                  </div>
                   <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name" autocomplete="off">
                  </div>
                   <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="id_username" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Date Of Birth</label>
                    <input type="date" class="form-control" placeholder="Date Of Birth" name="dob" max="1992-12-31">
                  </div>

                    <div class="form-group">
                    <label>Gender</label>
                    <select class="form-control" name="gender">
                            <option>Male</option>
                            <option>Female</option>
                            <option>Other</option>
                    </select>
                    </div>
                    <div class="form-group">
                    <label>Blood Group</label>
                    <input type="text" class="form-control" placeholder="Blood Group" name="blood_group" autocomplete="off" pattern="([AaBbOo]|[Aa][Bb])[\+-]">
                  </div>

                    <div class="form-group">
                    <label>Candidate ID</label>
                    <input type="text" class="form-control" placeholder="Candidate ID" name="candidate_number" id="id_candidate_number" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Encryption Message</label>
                    <input type="text" class="form-control" placeholder="Encryption Message" name="message" autocomplete="off">
                  </div>

                    <div class="form-group">
                    <label>Profile Picture</label>
                    <input type="file" class="form-control" placeholder="Upload Your Picture" name="profile_pic" required>
                  </div>

                    <div class="form-group">
                    <label>Phone Number</label>
                    <input type="tel" class="form-control" placeholder="Phone Number" name="ph_no" autocomplete="off" pattern="[0-9]{3}[0-9]{3}[0-9]{4}">
                  </div>
                  <div class="form-group">
                    <label>Address</label>
                    <input type="text" class="form-control" placeholder="Address" name="address" autocomplete="off">
                  </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add Candidate Details</button>
                    <button type="reset" class="btn btn-primary float-right">Reset</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

E_voting_system/E_voting_system_app/templates/admin_template/add_committee_template.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Add Committee Member
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Committee member</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_committee_save" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-body">
                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>
                  <div class="form-group">
                    <label>Email address</label>
                    <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email" autocomplete="off">
                  </div>
                  <div class="form-group">
                    <label>Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="first_name" autocomplete="off">
                  </div>
                   <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name" autocomplete="off">
                  </div>
                   <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="id_username" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>ECM ID</label>
                    <input type="text" class="form-control" placeholder="Enter ECM ID" name="committee_number" id="id_committee_number" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Date Of Birth</label>
                    <input type="date" class="form-control" placeholder="Date Of Birth" name="dob" max="1999-12-31">
                  </div>
                    <div class="form-group">
                    <label>Gender</label>
                    <select class="form-control" name="gender">
                            <option>Male</option>
                            <option>Female</option>
                            <option>Other</option>
                    </select>
                    </div>
                     <div class="form-group">
                    <label>Blood Group</label>
                    <input type="text" class="form-control" placeholder="Blood Group" name="blood_group" autocomplete="off" pattern="([AaBbOo]|[Aa][Bb])[\+-]">
                  </div>
                     <div class="form-group">
                    <label>Qualification</label>
                    <input type="text" class="form-control" placeholder="Qualification" name="qualification" autocomplete="off">
                  </div>
                        <div class="form-group">
                    <label>Profile Picture</label>
                    <input type="file" class="form-control" placeholder="Upload Your Picture" name="profile_pic" required>
                  </div>

                    <div class="form-group">
                    <label>Phone Number</label>
                    <input type="tel" class="form-control" placeholder="Phone Number" name="ph_no" autocomplete="off" pattern="[0-9]{3}[0-9]{3}[0-9]{4}">
                  </div>
                  <div class="form-group">
                    <label>Address</label>
                    <input type="text" class="form-control" placeholder="Address" name="address" autocomplete="off">
                  </div>


                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add Committee Member</button>
                    <button type="reset" class="btn btn-primary float-right">Reset</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

E_voting_system/E_voting_system_app/templates/admin_template/add_voter_template.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Add Voter
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Voter</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_voter_save" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-body">
                    <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                  <div class="form-group">
                    <label>Email address</label>
                    <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email" autocomplete="off">
                  </div>
                  <div class="form-group">
                    <label>Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="first_name" autocomplete="off">
                  </div>
                   <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name" autocomplete="off">
                  </div>
                   <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="id_username" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Date Of Birth</label>
                    <input type="date" class="form-control" placeholder="Date Of Birth" name="dob" max="2003-12-31">
                  </div>

                    <div class="form-group">
                    <label>Gender</label>
                    <select class="form-control" name="gender">
                            <option>Male</option>
                            <option>Female</option>
                            <option>Other</option>
                    </select>
                    </div>
                    <div class="form-group">
                    <label>Blood Group</label>
                    <input type="text" class="form-control" placeholder="Blood Group" name="blood_group" autocomplete="off"  pattern="([AaBbOo]|[Aa][Bb])[\+-]">
                  </div>

                    <div class="form-group">
                    <label>Voter ID</label>
                    <input type="text" class="form-control" placeholder="Voter ID" name="voter_number" id="id_voter_number" autocomplete="off">
                  </div>

                    <div class="form-group">
                    <label>Profile Picture</label>
                    <input type="file" class="form-control" placeholder="Upload Your Picture" name="profile_pic" required>
                  </div>

                    <div class="form-group">
                    <label>Phone Number</label>
                    <input type="tel" class="form-control" placeholder="Phone Number" name="ph_no" autocomplete="off" pattern="[0-9]{3}[0-9]{3}[0-9]{4}">
                  </div>
                  <div class="form-group">
                    <label>Address</label>
                    <input type="text" class="form-control" placeholder="Address" name="address" autocomplete="off">
                  </div>



                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add Voter Details</button>
                    <button type="reset" class="btn btn-primary float-right">Reset</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

E_voting_system/E_voting_system_app/templates/admin_template/admin_profile.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Dashboard
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">About Me</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{% url 'admin_profile_save' %}" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.username }}" disabled="disabled">
                  </div>
                  <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" value="{{ user.email }}" disabled="disabled">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}">
                  </div>
                  <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}">
                  </div>
                   <div class="form-group">
                    <label>Change Password?</label>
                    <input type="password" class="form-control" name="password" placeholder="Fill only if you want to change password">
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Save Profile</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

E_voting_system/E_voting_system_app/templates/admin_template/footer.html
 <footer class="main-footer">

  </footer>

E_voting_system/E_voting_system_app/templates/admin_template/form_template.html
<form role="form" action="{{ action_path }}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-body">
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">{{ button_text }}</button>
                    <button type="reset" class="btn btn-primary float-right">{{ button1_text }}</button>
                </div>
              </form>